- name: install software-properties-common
  apt:
    update_cache: yes
    name: software-properties-common
    state: present
    install_recommends: yes

- name: add mariadb repo key
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: "0xF1656F24C74CD1D8"
    state: present

- name: add mariadb ppa repo
  apt_repository:
    repo: "deb [arch=amd64,arm64,ppc64el] http://mirrors.tuna.tsinghua.edu.cn/mariadb/repo/{{ mariadb_version }}/ubuntu bionic main"
    state: present
    update_cache: yes

- name: install mariadb server
  apt:
    name: mariadb-server
    state: present

- name: replace mysql config
  template:
    src: my.cnf.j2
    dest: /etc/mysql/my.cnf
    mode: 0644

- name: restart mysql services
  systemd:
    name: mysql
    state: restarted

- name: change root password
  ignore_errors: yes
  command: mysqladmin -u root password "{{ mariadb_root_password }}"

- name: set .my.cnf file
  blockinfile:
    path: ~/.my.cnf
    create: yes
    block: |
      [client]
      user=root
      password="{{ mariadb_root_password }}"

- name: create sattar db
  command: mysql -e "CREATE DATABASE IF NOT EXISTS {{ item.name }};"
  with_items: "{{ mariadb_databases }}"

- name: create sattar user in mysql
  command: mysql -e "CREATE USER IF NOT EXISTS '{{ item.name }}'@'{{ item.host }}' IDENTIFIED BY '{{ item.password }}';"
  with_items: "{{ mariadb_users }}"

- name: grant all prev on sattar
  command: mysql -e "GRANT ALL PRIVILEGES ON {{ item.database }}.* TO '{{ item.name }}'@'{{ item.host }}';"
  with_items: "{{ mariadb_users }}"
